import './theme.css';

const fontUrl = 'https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;500;800&family=Suez+One&display=swap';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode,
}) {
  return (
    <html lang="en" className="base">
      <head>
        <link rel="preload" as="style" href={fontUrl} />
        <link rel="stylesheet" href={fontUrl} />
      </head>
      <body>{children}</body>
    </html>
  );
}
